# Generated by Django 5.1.7 on 2025-03-25 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoverCalendar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preventivemaintenance',
            name='maintenance_frequency_days',
        ),
    ]
