# Generated by Django 5.1.7 on 2025-03-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoverCalendar', '0002_remove_preventivemaintenance_maintenance_frequency_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('block_number', models.CharField(default='Block #', max_length=1)),
            ],
        ),
    ]
