# Generated by Django 5.1.7 on 2025-03-25 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoverCalendar', '0003_classblocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BlockAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.IntegerField()),
                ('cycle_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoverCalendar.cycleday')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoverCalendar.timeslot')),
            ],
            options={
                'unique_together': {('cycle_day', 'block_number'), ('cycle_day', 'time_slot')},
            },
        ),
    ]
