# Generated by Django 5.1.7 on 2025-03-26 01:01

from django.db import migrations


def update_full_schedule(apps, schema_editor):
    # Get model references
    CycleDay = apps.get_model('CoverCalendar', 'CycleDay')
    TimeSlot = apps.get_model('CoverCalendar', 'TimeSlot')
    BlockAssignment = apps.get_model('CoverCalendar', 'BlockAssignment')
    
    # Clear existing assignments to avoid conflicts
    BlockAssignment.objects.all().delete()
    
    # Full 7-day cycle schedule
    cycle_schedules = {
        # Day 1: Regular order
        1: [(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)],
        
        # Day 2: Shifted by 1
        2: [(1, 7), (2, 1), (3, 2), (4, 3), (5, 4), (6, 5)],
        
        # Day 3: Shifted by 2
        3: [(1, 6), (2, 7), (3, 1), (4, 2), (5, 3), (6, 4)],
        
        # Day 4: Shifted by 3
        4: [(1, 5), (2, 6), (3, 7), (4, 1), (5, 2), (6, 3)],
        
        # Day 5: Shifted by 4
        5: [(1, 4), (2, 5), (3, 6), (4, 7), (5, 1), (6, 2)],
        
        # Day 6: Shifted by 5
        6: [(1, 3), (2, 4), (3, 5), (4, 6), (5, 7), (6, 1)],
        
        # Day 7: Shifted by 6
        7: [(1, 2), (2, 3), (3, 4), (4, 5), (5, 6), (6, 7)]
    }
    
    # Create all block assignments
    for day_num, schedule in cycle_schedules.items():
        day = CycleDay.objects.get(day_number=day_num)
        for period_num, block_num in schedule:
            time_slot = TimeSlot.objects.filter(period_number=period_num).first()
            if time_slot:
                BlockAssignment.objects.create(
                    cycle_day=day,
                    time_slot=time_slot,
                    block_number=block_num
                )


def reverse_update(apps, schema_editor):
    # Reversing this migration would just delete all assignments
    # A more complex reversal could restore just the Day 5 assignments if needed
    BlockAssignment = apps.get_model('CoverCalendar', 'BlockAssignment')
    BlockAssignment.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('CoverCalendar', '0005_populate_schedule_data'),
    ]

    operations = [
        migrations.RunPython(update_full_schedule, reverse_update),
    ]
