# Generated by Django 5.1.7 on 2025-03-27 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoverCalendar', '0006_update_full_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreventiveMaintenance',
        ),
    ]
