# Generated by Django 5.1.7 on 2025-03-27 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoverCalendar', '0009_migrate_to_new_day_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_of_week', models.IntegerField()),
                ('is_special_schedule', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='WorkWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkTimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('period_name', models.CharField(max_length=100)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('work_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_blocks', to='CoverCalendar.workday')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.AddField(
            model_name='workday',
            name='work_week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='CoverCalendar.workweek'),
        ),
        migrations.AlterUniqueTogether(
            name='workday',
            unique_together={('work_week', 'date'), ('work_week', 'day_of_week')},
        ),
    ]
