# Generated by Django 5.1.7 on 2025-03-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoverCalendar', '0011_remove_work_week_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleGenerationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Start date for generating cycles')),
                ('end_date', models.DateField(help_text='End date for generating cycles')),
                ('cycle_length', models.IntegerField(default=7, help_text='Number of days in each cycle')),
                ('active', models.BooleanField(default=True, help_text='Whether these settings are active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cycle Generation Settings',
                'verbose_name_plural': 'Cycle Generation Settings',
                'ordering': ['-created_at'],
            },
        ),
    ]
