# Generated by Django 5.1.7 on 2025-03-28 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoverCalendar', '0012_add_cycle_generation_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='generation_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='CoverCalendar.cyclegenerationsettings'),
        ),
    ]
