# Generated by Django 5.1.7 on 2025-04-03 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoverCalendar', '0013_add_cycle_generation_settings_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('request_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_requests', to='CoverCalendar.timeblock')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('time_block', 'request_date')},
            },
        ),
    ]
