# Generated by Django 5.1.7 on 2025-04-03 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoverCalendar', '0014_add_coverage_request_model'),
        ('CoverCalendar', '0014_coveragerequest'),
    ]

    operations = [
    ]
