# Generated by Django 5.1.7 on 2025-04-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoverCalendar', '0015_merge_20250402_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveragerequest',
            name='is_fulfilled',
            field=models.BooleanField(default=False, help_text='Whether this coverage request has been fulfilled'),
        ),
        migrations.AddField(
            model_name='coveragerequest',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes for the coverage request', null=True),
        ),
    ]
