# Generated by Django 5.1.7 on 2025-04-03 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoverCalendar', '0016_add_coverage_request_notes_fulfilled'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coveragerequest',
            unique_together=set(),
        ),
    ]
