# Generated by Django 5.1.7 on 2025-04-03 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoverCalendar', '0019_teachercoverage_display_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blockassignment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='blockassignment',
            name='cycle_day',
        ),
        migrations.RemoveField(
            model_name='blockassignment',
            name='time_slot',
        ),
        migrations.DeleteModel(
            name='ClassBlocks',
        ),
        migrations.DeleteModel(
            name='CycleDay',
        ),
        migrations.DeleteModel(
            name='BlockAssignment',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
